// Generated by BUCKLESCRIPT VERSION 2.0.1, PLEASE EDIT WITH CARE
'use strict';


var videoFileTypes = /* :: */[
  "mov",
  /* :: */[
    "mp4",
    /* :: */[
      "avi",
      /* :: */[
        "mkv",
        /* [] */0
      ]
    ]
  ]
];

var imageFileTypes = /* :: */[
  "pgm",
  /* :: */[
    "ppm",
    /* :: */[
      "pam",
      /* :: */[
        "pgmyuv",
        /* :: */[
          "jpeg",
          /* :: */[
            "jpg",
            /* :: */[
              "gif",
              /* :: */[
                "png",
                /* :: */[
                  "tiff",
                  /* :: */[
                    "sgi",
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var soundFileTypes = /* :: */[
  "wav",
  /* :: */[
    "mp3",
    /* :: */[
      "aac",
      /* :: */[
        "ogg",
        /* [] */0
      ]
    ]
  ]
];

exports.videoFileTypes = videoFileTypes;
exports.imageFileTypes = imageFileTypes;
exports.soundFileTypes = soundFileTypes;
/* No side effect */
