/* @flow */

import {
  convertToVideo,
  convertToImages,
  convertToAudio,
  concatVideo,
  convertToGif,
} from './commands';

import {
  FFMPEG,
  INPUT,
  addInput,
  overwriteVideo,
  maxFileSize,
  frames,
  videoFrames,
  audioFrames,
  startTime,
  duration,
  framesPerSecond,
  disable,
  disableVideo,
  disableAudio,
  muteVideo,
  volume,
  setVideoSize,
  setVideoSpeed,
  setAudioSpeed,
  loopVideo,
  setCodec,
  setAudioCodec,
  setVideoCodec,
  setBitrate,
  setAudioBitrate,
  setVideoBitrate,
  setVariableBitrate,
  setMetaData,
  setCreationTime,
} from './options';

export {
  convertToVideo,
  convertToImages,
  convertToAudio,
  concatVideo,
  convertToGif,
  FFMPEG,
  INPUT,
  addInput,
  overwriteVideo,
  maxFileSize,
  frames,
  videoFrames,
  audioFrames,
  startTime,
  duration,
  framesPerSecond,
  disable,
  disableVideo,
  disableAudio,
  muteVideo,
  volume,
  setVideoSize,
  setVideoSpeed,
  setAudioSpeed,
  loopVideo,
  setCodec,
  setAudioCodec,
  setVideoCodec,
  setBitrate,
  setAudioBitrate,
  setVideoBitrate,
  setVariableBitrate,
  setMetaData,
  setCreationTime,
};

