// Generated by BUCKLESCRIPT VERSION 2.0.1, PLEASE EDIT WITH CARE
'use strict';

var Options$Fffmpeg = require("./options.js");

var ffmpeg = Options$Fffmpeg.ffmpeg;

var inputFlag = Options$Fffmpeg.inputFlag;

var addInput = Options$Fffmpeg.addInput;

var overwriteVideo = Options$Fffmpeg.overwriteVideo;

var maxFileSize = Options$Fffmpeg.maxFileSize;

var frames = Options$Fffmpeg.frames;

var videoFrames = Options$Fffmpeg.videoFrames;

var audioFrames = Options$Fffmpeg.audioFrames;

var startTime = Options$Fffmpeg.startTime;

var seek = Options$Fffmpeg.seek;

var duration = Options$Fffmpeg.duration;

var framesPerSecond = Options$Fffmpeg.framesPerSecond;

var disable = Options$Fffmpeg.disable;

var disableVideo = Options$Fffmpeg.disableVideo;

var disableAudio = Options$Fffmpeg.disableAudio;

var muteVideo = Options$Fffmpeg.muteVideo;

var volume = Options$Fffmpeg.volume;

var setVideoSpeed = Options$Fffmpeg.setVideoSpeed;

var setAudioSpeed = Options$Fffmpeg.setAudioSpeed;

var setCodec = Options$Fffmpeg.setCodec;

var setAudioCodec = Options$Fffmpeg.setAudioCodec;

var setVideoCodec = Options$Fffmpeg.setVideoCodec;

var setBitrate = Options$Fffmpeg.setBitrate;

var setVideoBitrate = Options$Fffmpeg.setVideoBitrate;

var setAudioBitrate = Options$Fffmpeg.setAudioBitrate;

var setVariableBitrate = Options$Fffmpeg.setVariableBitrate;

var metaDataFlag = Options$Fffmpeg.metaDataFlag;

exports.ffmpeg             = ffmpeg;
exports.inputFlag          = inputFlag;
exports.addInput           = addInput;
exports.overwriteVideo     = overwriteVideo;
exports.maxFileSize        = maxFileSize;
exports.frames             = frames;
exports.videoFrames        = videoFrames;
exports.audioFrames        = audioFrames;
exports.startTime          = startTime;
exports.seek               = seek;
exports.duration           = duration;
exports.framesPerSecond    = framesPerSecond;
exports.disable            = disable;
exports.disableVideo       = disableVideo;
exports.disableAudio       = disableAudio;
exports.muteVideo          = muteVideo;
exports.volume             = volume;
exports.setVideoSpeed      = setVideoSpeed;
exports.setAudioSpeed      = setAudioSpeed;
exports.setCodec           = setCodec;
exports.setAudioCodec      = setAudioCodec;
exports.setVideoCodec      = setVideoCodec;
exports.setBitrate         = setBitrate;
exports.setVideoBitrate    = setVideoBitrate;
exports.setAudioBitrate    = setAudioBitrate;
exports.setVariableBitrate = setVariableBitrate;
exports.metaDataFlag       = metaDataFlag;
/* No side effect */
