// Generated by BUCKLESCRIPT VERSION 2.0.1, PLEASE EDIT WITH CARE
'use strict';


function includes(arr, str) {
  return +arr.includes(str);
}

function concat(a, b) {
  return a + " " + b;
}

function optionsString(param) {
  return param.reduce(concat, "");
}

function optionsNumber(param) {
  return param.reduce((function (a, b) {
                return a + b | 0;
              }), 0);
}

var hello = optionsString(/* array */[
      "1",
      "2",
      "3"
    ]);

var helloNum = optionsNumber(/* int array */[
      1,
      2,
      3
    ]);

console.log(hello);

console.log(helloNum);

exports.includes      = includes;
exports.concat        = concat;
exports.optionsString = optionsString;
exports.optionsNumber = optionsNumber;
exports.hello         = hello;
exports.helloNum      = helloNum;
/* hello Not a pure module */
