// Generated by BUCKLESCRIPT VERSION 2.0.1, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function includes(arr, str) {
  return +arr.includes(str);
}

function concat(a, b) {
  return a + " " + b;
}

function optionsString(param) {
  return List.fold_left(concat, "", param);
}

exports.includes      = includes;
exports.concat        = concat;
exports.optionsString = optionsString;
/* No side effect */
